### ISSUE TITLE
Agregar al eventoDTO cuando esta deshabilitado

### ISSUE THREAD

**Issue by LUGANT** [unsam-proyecto-grupo-5-2024/unsam-proyecto-back#72]
Cuando envie una solicitud

**Comment by NicoMasuyama** [comment]
Se creo el eventoHomeDTO que también recibe el usuarioId del que está loggeado, para ver si ese usuario puede hacer una solicitud a un evento. El eventoDetalladoDTO ahora también recibe el usuarioId para el mismo proposito
